[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }

[dev-dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
